[package]
name = "vaultwarden"
version = "1.2.0"
authors = ["Daniel García <dani-garcia@users.noreply.github.com>"]
edition = "2024"
rust-version = "1.90"
resolver = "3"

repository = "https://github.com/dani-garcia/vaultwarden"
readme = "README.md"
license = "AGPL-3.0-only"
publish = false
build = "build.rs"

[features]

[dependencies]
log = "0.4"
once_cell = "1.21"
url = "2.5"
argon2 = "0.5"
semver = "1.0"
dashmap = "6.2"
uuid = { version = "1.11", features = ["v4", "serde"] }
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4", "with-uuid-1", "with-serde_json-1"] }
refinery = { version = "0.8", features = ["tokio-postgres"] }
bb8 = "0.9"
bb8-postgres = "0.9"
jwt = "0.16"
always_cell = "0.1"
ipnetwork = { version = "0.21", features = ["serde"] }
serde_with = "3.12"
anyhow = "1.0"
serde_yaml = "0.9"
async-trait = "0.1"
indexmap = { version = "2.7", features = ["serde"] }
lazy_static = "1.4"
strum = { version = "0.28", features = ["derive"] }
mime_guess = "2.0.4"
mime = "0.3.17"
smallvec = { version = "1.15", features = ["write"] }
serde_repr = "0.1"
serde-aux = "4.5"
hex = "0.4"
varint-rs = "2.2.0"
axol = { version = "0.2.0", git = "https://github.com/Protryon/axol.git" }

jsonwebtoken = { version = "10.4", default-features = false, features = ["rust_crypto", "use_pem"] }

fern = { version = "0.7", features = [] }
tokio-tungstenite = "0.28"
rmpv = "1.3"
futures = "0.3.31"
tokio = { version = "1.47", features = ["rt-multi-thread", "fs", "io-util", "parking_lot", "time", "signal"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.135"
rand = "0.10"
ring = "0.17"
chrono = { version = "0.4.39", features = ["clock", "serde"], default-features = false }
chrono-tz = "0.10"
job_scheduler_ng = "2.0.4"
data-encoding = "2.6"
totp-lite = "2.0.1"
yubico = { package = "yubico_ng", version = "0.15", features = ["online-tokio"], default-features = false }
webauthn-rs = { version = "0.5.5", features = ["danger-allow-state-serialisation", "danger-credential-internals"] }
webauthn-rs-proto = "0.5.5"
webauthn-rs-core = "0.5.5"
lettre = { version = "0.11", features = ["smtp-transport", "sendmail-transport", "builder", "serde", "tokio1-native-tls", "hostname", "tracing", "tokio1"], default-features = false }
percent-encoding = "2.3" # URL encoding library used for URL's in the emails
email_address = "0.2.9"
handlebars = { version = "6.3", features = ["dir_source"] }
reqwest = { version = "0.12", features = ["stream", "json", "gzip", "brotli", "socks", "cookies", "hickory-dns"] }
html5gum = "0.8"
regex = { version = "1.11", features = ["std", "perf", "unicode-perl"], default-features = false }
data-url = "0.3"
bytes = "1.9"
cached = { version = "0.55", features = ["async"] }
#TODO: remove
cookie = "0.18"
#TODO: remove
cookie_store = "0.21"
openssl = "0.10"
governor = "0.8"
openidconnect = "4.0"

tracing-opentelemetry = "0.33"
tracing-subscriber = "0.3.17"
opentelemetry = "0.32"
opentelemetry_sdk = { version = "0.32", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.32", features = ["grpc-tonic"] }
tracing = { version = "0.1", features = ["log-always", "release_max_level_debug"]}


# Strip debuginfo from the release builds
# Also enable thin LTO for some optimizations
[profile.release]
strip = "debuginfo"
lto = "thin"

# Always build argon2 using opt-level 3
# This is a huge speed improvement during testing
[profile.dev.package.argon2]
opt-level = 3

# A little bit of a speedup
[profile.dev]
split-debuginfo = "unpacked"
